"""Gate for the importance scoring.

A percentile rank must preserve the order of what it ranks. The version that
shipped for eight sprints did not: it handed each tied value its own position,
and since the sort is stable those positions followed the input order — which
here is the order statements were derived in.

That was not a rounding-level problem. On the reference corpus 1832 of 1904
statements share a single value on four of the six components, so for most of
the corpus those components recorded where a statement appeared rather than
anything about it. The defect turned out to be *understating* the result: with
ties sharing a rank, cross-member rank correlation moved from 0.40 to 0.81 and
the range narrowed from [-0.77, 1.0] to [-0.03, 1.0].

`test_normalization_preserves_order` is the check that it stays fixed.
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from scipy.stats import spearmanr  # noqa: E402

from pipeline.report import importance as I  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]


def test_ties_share_a_rank():
    """Equal inputs must get equal outputs. Nothing else breaks order."""
    assert I._rank_normalize([5, 5, 5, 5]) == [0.5, 0.5, 0.5, 0.5]
    out = I._rank_normalize([0, 0, 0, 1])
    assert out[0] == out[1] == out[2], out
    assert out[3] > out[0]


def test_normalization_preserves_order():
    """The property a percentile rank has by definition, pinned as a test.

    Checked on a heavy tie mass, because that is the shape the real corpus has
    and the shape the broken version mishandled.
    """
    for values in (
        [3, 1, 4, 2],
        [0] * 20 + [1, 2, 3],
        [7, 7, 1, 9, 1, 1],
        list(range(50)) + [0] * 200,
    ):
        out = I._rank_normalize(values)
        rho = spearmanr(values, out).statistic
        assert abs(rho - 1.0) < 1e-12, f"normalization reordered {values[:8]}...: rho={rho}"


def test_degenerate_inputs():
    assert I._rank_normalize([]) == []
    assert I._rank_normalize([7]) == [0.0]


def test_stored_ranking_is_order_preserving():
    """The same property, verified on the artifact rather than on a fixture.

    A ranking regenerated by an older version of the scorer would fail here even
    though the code is correct, which is the point: the check is on what is
    actually on disk and being reported.
    """
    p = ROOT / "runs" / "main" / "importance.json"
    if not p.exists():
        print("  (no stored ranking; skipping)")
        return
    ranked = json.loads(p.read_text())
    for c in I.COMPONENTS:
        raw = [r["raw"][c] for r in ranked]
        norm = [r["components"][c] for r in ranked]
        if len(set(raw)) < 2:
            continue
        rho = spearmanr(raw, norm).statistic
        assert abs(rho - 1.0) < 1e-9, (
            f"stored ranking has {c} out of order (rho={rho:.4f}); "
            f"re-run tools/rescore_importance.py"
        )


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_"):
            fn()
            print(f"ok  {name}")
