"""Apply the admissibility rule and say yes or no.

The rule is fixed here, in code, and was written before any candidate had been
measured. That ordering is the point: a bar chosen after seeing the numbers is
not a bar. If a candidate fails, the report names the first failing condition
rather than printing a table and leaving the reader to infer the verdict.

Usage:
  python3 -m pipeline.admissibility.verdict --candidate candidate
"""

import argparse
import json
import pathlib

from .probe import AXES

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "runs" / "admissibility"

REQUIRED_AXES_WON = 3


def wins(cand_axis, base_axis):
    """A win requires the ranges not to overlap.

    Means alone would let ordinary seed variance decide admissibility, and seed
    variance in this pipeline is larger than most of the effects it is asked to
    detect. Disjoint ranges over the same seed set is a weak claim, deliberately:
    four seeds cannot support a stronger one.
    """
    return cand_axis["min"] > base_axis["max"]


def evaluate(candidate, baseline, calibrated=None):
    axis_rows = []
    won = 0
    for axis in AXES:
        c, b = candidate["axes"][axis], baseline["axes"][axis]
        w = wins(c, b)
        won += w
        axis_rows.append(
            {
                "axis": axis,
                "candidate": [c["min"], c["max"]],
                "baseline": [b["min"], b["max"]],
                "candidate_mean": c["mean"],
                "baseline_mean": b["mean"],
                "won": w,
            }
        )

    conditions = [
        (
            "richer on a majority of axes",
            won >= REQUIRED_AXES_WON,
            f"won {won} of {len(AXES)}; needs {REQUIRED_AXES_WON} with disjoint ranges",
        ),
        (
            "no inert axiom",
            not candidate["inert_axioms"],
            f"inert: {candidate['inert_axioms']}",
        ),
        (
            "concept miner produces candidates",
            candidate["axes"]["concept_candidates"]["min"] > 0,
            f"minimum across seeds is {candidate['axes']['concept_candidates']['min']}",
        ),
        (
            "target calibration succeeds",
            bool(calibrated) if calibrated is not None else None,
            "not evaluated" if calibrated is None else f"calibrated={bool(calibrated)}",
        ),
    ]

    failed = [name for name, ok, _ in conditions if ok is False]
    unevaluated = [name for name, ok, _ in conditions if ok is None]
    admissible = not failed and not unevaluated

    return {
        "candidate": candidate["label"],
        "baseline": baseline["label"],
        "seeds": candidate["seeds"],
        "budget": candidate["budget"],
        "axes": axis_rows,
        "axes_won": won,
        "conditions": [
            {"condition": n, "passed": ok, "detail": d} for n, ok, d in conditions
        ],
        "first_failing_condition": failed[0] if failed else None,
        "unevaluated_conditions": unevaluated,
        "admissible": admissible,
        "cost": {
            "candidate_seconds": candidate.get("seconds"),
            "baseline_seconds": baseline.get("seconds"),
        },
    }


def render(v, candidate, baseline):
    L = []
    w = L.append
    w("# Admissibility of a candidate control domain")
    w("")
    w("Generated by `pipeline.admissibility.verdict`. Every number here is a")
    w("measurement, not an argument, and the rule below was fixed in code before")
    w("any candidate was measured.")
    w("")
    w(f"**Verdict: {'ADMISSIBLE' if v['admissible'] else 'NOT ADMISSIBLE'}**")
    if v["first_failing_condition"]:
        w("")
        w(f"First failing condition: *{v['first_failing_condition']}*.")
    if v["unevaluated_conditions"]:
        w("")
        w(f"Conditions not evaluated: {v['unevaluated_conditions']}. A condition that")
        w("was not checked is not a condition that passed.")
    w("")

    w("## Why this gate exists")
    w("")
    w("An earlier attempt at a control was built without one. It had fewer")
    w("relations and fewer axioms than the theory under test, so it could not")
    w("have shown whether that theory is too poor in either direction, and three")
    w("further blockers were each independently fatal. The cost of discovering")
    w("that afterwards was a sprint; the cost of measuring it first is minutes.")
    w("")

    w("## Richness, measured as structure found per unit budget")
    w("")
    w(f"Both theories under one budget and the same seeds {v['seeds']}. A win")
    w("requires the candidate's range to be disjoint from the baseline's, not")
    w("merely a better mean — seed variance here is larger than most effects.")
    w("")
    w("| axis | candidate | baseline | won |")
    w("|---|---|---|---|")
    for r in v["axes"]:
        w(f"| {r['axis']} | {r['candidate'][0]}–{r['candidate'][1]} "
          f"(mean {r['candidate_mean']}) | {r['baseline'][0]}–{r['baseline'][1]} "
          f"(mean {r['baseline_mean']}) | {'yes' if r['won'] else 'no'} |")
    w("")
    w(f"Axes won: **{v['axes_won']} of {len(v['axes'])}**, threshold {REQUIRED_AXES_WON}.")
    w("")

    w("## Conditions")
    w("")
    w("| condition | passed | detail |")
    w("|---|---|---|")
    for c in v["conditions"]:
        state = {True: "yes", False: "**no**", None: "not evaluated"}[c["passed"]]
        w(f"| {c['condition']} | {state} | {c['detail']} |")
    w("")

    w("## Axiom liveness")
    w("")
    w("An axiom that is neither a rule nor deliberately seeded contributes")
    w("nothing however long the search runs, and the only symptom is a slightly")
    w("smaller corpus — indistinguishable from seed variance. That is what the")
    w("previous candidate's identity axiom did.")
    w("")
    w("Contributing nothing *at this budget* is a different thing and is not a")
    w("failure: the baseline has three such axioms, and a rule that failed the")
    w("baseline would be the wrong rule.")
    w("")
    for label, rep in (("candidate", candidate), ("baseline", baseline)):
        w(f"- {label}: inert {rep['inert_axioms'] or 'none'}; "
          f"idle at this budget {rep['idle_at_this_budget'] or 'none'}")
    w("")

    w("## Cost")
    w("")
    cost = v["cost"]
    w(f"Probe runtime: candidate {cost['candidate_seconds']}s, baseline "
      f"{cost['baseline_seconds']}s, at the same budget.")
    w("")
    if cost["candidate_seconds"] and cost["baseline_seconds"]:
        ratio = cost["candidate_seconds"] / max(cost["baseline_seconds"], 0.01)
        if ratio > 5:
            w(f"The candidate costs roughly {ratio:.0f}x the baseline for the same")
            w("budget. That is a property of the theory rather than of the probe,")
            w("and it belongs in the record: whatever this candidate is measured")
            w("on later, the grid it would need is that much more expensive.")
            w("")

    w("## What this does not establish")
    w("")
    w("The probe never invokes the proof checker. It measures what the search")
    w("reaches, not what is true, and no statement it derives is claimed. An")
    w("admitted candidate has its corpus kernel-verified in the build that")
    w("follows, like everything else in this project.")
    w("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidate", default="candidate")
    ap.add_argument("--baseline", default="incumbent")
    ap.add_argument("--calibrated", type=int, default=None,
                    help="1 or 0: whether target calibration succeeded for the candidate")
    args = ap.parse_args()

    cand = json.loads((OUT / f"probe-{args.candidate}.json").read_text())
    base = json.loads((OUT / f"probe-{args.baseline}.json").read_text())

    calibrated = None if args.calibrated is None else bool(args.calibrated)
    v = evaluate(cand, base, calibrated)

    (OUT / "verdict.json").write_text(json.dumps(v, indent=1) + "\n")
    doc = ROOT / "docs" / "admissibility.md"
    doc.write_text(render(v, cand, base))

    print(f"verdict: {'ADMISSIBLE' if v['admissible'] else 'NOT ADMISSIBLE'}")
    if v["first_failing_condition"]:
        print(f"  first failing condition: {v['first_failing_condition']}")
    if v["unevaluated_conditions"]:
        print(f"  not evaluated: {v['unevaluated_conditions']}")
    print(f"  axes won: {v['axes_won']}/{len(v['axes'])}")
    print(f"wrote {OUT}/verdict.json and {doc}")


if __name__ == "__main__":
    main()
